version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu

# 수명 주기
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 180
      runas: ubuntu